#!/usr/bin/env bash

# Apply some simple textual replacements

sed -e 's/\\begin{verbatim}/\\begin{minted}{r}/' \
    -e 's/\\end{verbatim}/\\end{minted}/' \
    -e 's/\\begin{longtable}\[c\]/\\begin{tabular}/' \
    -e 's/\\end{longtable}/\\end{tabular}/'
